DEVICE_PATH := device/xiaomi/a5

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic

TARGET_USES_64_BIT_BINDER := true
TARGET_SUPPORTS_64_BIT_APPS := true

# Platform / Chipset (Unisoc T7250)
TARGET_BOARD_PLATFORM := sharkl5pro
TARGET_BOOTLOADER_BOARD_NAME := a5
TARGET_NO_BOOTLOADER := true

# Kernel & DTB (Using generic values - adjust if you have specific offsets)
BOARD_KERNEL_PAGESIZE := 2048
BOARD_BOOT_HEADER_VERSION := 2
BOARD_MKBOOTIMG_ARGS := --header_version $(BOARD_BOOT_HEADER_VERSION)

# Partitions (A/B & Dynamic)
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_HAS_LARGE_FILESYSTEM := true

# Virtual A/B & Dynamic Partitions
BOARD_SUPER_PARTITION_GROUPS := xiaomi_dynamic_partitions
BOARD_XIAOMI_DYNAMIC_PARTITIONS_SIZE := 9126805504
BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST := system system_ext product vendor
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext

# Recovery File System
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"

# PitchBlack Recovery Project (PBRP) Specific Flags
TW_THEME := portrait_hdpi
TW_DEVICE_VERSION := 1
PB_RECOVERY_DEVICE := a5
PB_DEVICE_MODEL := "Redmi A5"
PB_MAINTAINER := "khyprogrammer"
PB_BUILD_TYPE := Unofficial
PB_OFFICIAL := false

# A/B & Encryption Support for PBRP
PB_AB_DEVICE := true
PB_VIRTUAL_AB_DEVICE := true
PB_DISABLE_ENCRYPTION_CHECK := true
PB_DISABLE_REBOOT_BOOTLOADER := true

# Display
TW_BRIGHTNESS_PATH := "/sys/class/backlight/backlight/brightness"
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 150
