#
# Copyright (C) 2026 The Android Open Source Project
#
# SPDX-License-Identifier: Apache-2.0
#
# Path to device tree
DEVICE_PATH := device/xiaomi/a5

# Platform
TARGET_BOARD_PLATFORM := ums9230
TARGET_BOOTLOADER_BOARD_NAME := a5

# Kernel (prebuilt)
TARGET_FORCE_PREBUILT_KERNEL := true
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_KERNEL_IMAGE_NAME := kernel

# Recovery image settings
BOARD_RECOVERY IMAGE_PARTITION_SIZE := 67108864   # 64 MB
BOARD_FLASH_BLOCK_SIZE := 131072                # (block size * pagesize)

# File system support
BOARD_HAS_NO_REAL_SDCARD := true
BOARD_SUPPRESS_SECURE_ERASE := true
BOARD_USES_RECOVERY_AS_BOOT := false

# Partitions (Unisoc typical layout, adjust if needed)
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432      # 32 MB
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1073741824  # 1 GB
BOARD_VENDORIMAGE_PARTITION_SIZE := 536870912   # 512 MB
BOARD_USERDATAIMAGE_PARTITION_SIZE := 4294967296 # 4 GB

# File system types
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4

# OrangeFox specific flags
FOX_RECOVERY_INSTALLER := 1
FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER := 1
FOX_USE_NANO_EDITOR := 1
FOX_USE_BASH := 1
FOX_USE_TAR_BINARY := 1
FOX_USE_XZ_UTILS := 1
FOX_USE_ZIP_BINARY := 1
FOX_USE_SED_BINARY := 1
FOX_USE_BUSYBOX := 1
FOX_USE_GREP_BINARY := 1
FOX_USE_FIND_BINARY := 1
FOX_USE_UNZIP_BINARY := 1
FOX_ENABLE_APP_MANAGER := 1
FOX_USE_MAGISKBOOT := 1
FOX_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1

# Primary architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := cortex-a55
TARGET_CPU_ABI := arm64-v8a

# Secondary architecture (32-bit support for Android Go)
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT :=  armv8-2a
TARGET_2ND_CPU_VARIANT := cortex-a55
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi

# Disable 64-bit app support (Android Go device)
TARGET_SUPPORTS_64_BIT_APPS := false

# Vendor image output path
TARGET_COPY_OUT_VENDOR := vendor

TW_MAX_BRIGHTNESS := 255






